export const product = [
  {
    name: "Iphone 15",
    price: "Rs. 110000",
    brand: "Apple",
    Category: "smartphone",
    stock: "20",
  },
   {
    name: "OnePlus 15",
    price: "Rs. 95000",
    brand: "OnePlus",
    Category: "smartphone",
    stock: "12",
  },
   {
    name: "Iphone 15 Pro",
    price: "Rs. 125000",
    brand: "Apple",
    Category: "smartphone",
    stock: "13",
  },
   {
    name: "Lenovo Loq",
    price: "Rs. 200000",
    brand: "Lenovo",
    Category: "Laptop",
    stock: "5",
  },
   {
    name: "ASUS ROG Strix G16 ",
    price: "Rs. 250000",
    brand: "ASUS",
    Category: "Laptop",
    stock: "20",
  },
   {
    name: "ASUS Monitor",
    price: "Rs. 50000",
    brand: "ASUS",
    Category: "Monitor",
    stock: "3",
  },
   {
    name: "Redmi 15",
    price: "Rs. 40000",
    brand: "Redmi",
    Category: "smartphone",
    stock: "25",
  },
];
